spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:./gateway
    username: sa
    #generate-unique-name: false
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.H2Dialect

kafka:
  address: localhost:29092
  groupId: group-2
  concurrencyCount: 3
  topic:
    x: x
    y: y
    z: z